### PR TITLE
Include guardnode

### PR DESCRIPTION
**Pull request by nkostoulas**

### CODE REVIEW

**Comment by nkostoulas** [comment]
don't merge yet

**Comment by nkostoulas** [comment]
@tomossomot can you check if it's ok

**Comment by nkostoulas** [comment]
@stakauskas will this:
```
    depends_on:
      - ocean
```
be enough if the guardnode daemon needs to wait for ocean to load? Is there another way to add a small time delay, as the node wallet might take more time in the future?

**Comment by tomossomot** [comment]
Cool i'm happy with this now

**Pull request merged**
